import React, { useState, useEffect } from 'react';
import { User, Key, Eye, EyeOff, Copy, Check, ShieldCheck, Activity, Clock } from 'lucide-react';
import { motion } from 'motion/react';
import { cn } from './ui/Library';
import { toast } from 'sonner';
import { getMe, getStatus, getTenantKey } from '../../api/client';

interface MeData {
  key_id: string;
  tenant_id: string;
  name: string;
  created_at?: string;
}

interface StatusData {
  capsule_count: number;
  total_storage_mb: string;
  buffer_events: number;
  auto_seal: {
    enabled: boolean;
    interval_seconds: number;
    last_seal: string | null;
  };
}

export const Settings: React.FC = () => {
  const [showApiKey, setShowApiKey] = useState(false);
  const [keyCopied, setKeyCopied] = useState(false);
  const [me, setMe] = useState<MeData | null>(null);
  const [status, setStatus] = useState<StatusData | null>(null);
  const [loading, setLoading] = useState(true);
  const storedKey = getTenantKey() || '';

  useEffect(() => {
    const fetchData = async () => {
      const [meRes, statusRes] = await Promise.all([getMe(), getStatus()]);
      if (meRes.ok && meRes.data) setMe(meRes.data as any);
      if (statusRes.ok && statusRes.data) setStatus(statusRes.data as any);
      setLoading(false);
    };
    fetchData();
  }, []);

  const handleCopyKey = () => {
    navigator.clipboard.writeText(storedKey);
    setKeyCopied(true);
    toast.success('API key copied to clipboard');
    setTimeout(() => setKeyCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="w-8 h-8 border-2 border-app-teal-accent/30 border-t-app-teal-accent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6 md:space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div>
        <h1 className="text-2xl md:text-4xl font-bold text-white tracking-tight">Settings</h1>
        <p className="text-zinc-500 mt-2 text-sm md:text-base">
          Identity from <code className="text-app-teal-accent/60 bg-app-teal-accent/5 px-1.5 py-0.5 rounded text-[11px]">GET /api/v1/me</code> &amp; status from <code className="text-app-teal-accent/60 bg-app-teal-accent/5 px-1.5 py-0.5 rounded text-[11px]">GET /api/v1/status</code>
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 md:gap-8">
        <div className="p-6 md:p-8 rounded-2xl bg-[#121214] border border-zinc-800 space-y-6">
          <h3 className="text-lg font-bold text-white flex items-center gap-2 pb-4 border-b border-zinc-800/50">
            <User className="w-5 h-5 text-app-teal-accent" /> Tenant Identity
          </h3>
          <div className="space-y-4">
            <SettingsRow label="Tenant Name" value={me?.name || '—'} />
            <SettingsRow label="Tenant ID" value={me?.tenant_id || '—'} mono />
            <SettingsRow label="Key ID" value={me?.key_id || '—'} mono />
            {me?.created_at && <SettingsRow label="Created" value={new Date(me.created_at).toLocaleString()} mono />}
          </div>
        </div>

        <div className="p-6 md:p-8 rounded-2xl bg-[#121214] border border-zinc-800 space-y-6">
          <h3 className="text-lg font-bold text-white flex items-center gap-2 pb-4 border-b border-zinc-800/50">
            <Key className="w-5 h-5 text-app-teal-accent" /> Current API Key
          </h3>
          <div className="space-y-4">
            <div className="bg-black/50 border border-zinc-800 rounded-xl px-4 py-3 flex items-center justify-between gap-3">
              <span className="font-mono text-xs text-zinc-400 break-all flex-1">
                {showApiKey ? storedKey : (storedKey.slice(0, 4) + '\u2022'.repeat(Math.max(storedKey.length - 4, 20)))}
              </span>
              <div className="flex items-center gap-2 flex-shrink-0">
                <button onClick={() => setShowApiKey(!showApiKey)} className="p-1.5 text-zinc-500 hover:text-white transition-colors">
                  {showApiKey ? <EyeOff size={15} /> : <Eye size={15} />}
                </button>
                <button onClick={handleCopyKey} className="p-1.5 text-zinc-500 hover:text-app-teal-accent transition-colors">
                  {keyCopied ? <Check size={15} className="text-app-teal-accent" /> : <Copy size={15} />}
                </button>
              </div>
            </div>
            <p className="text-[10px] text-zinc-600 leading-relaxed">
              This key was generated by your agent via <code className="text-app-teal-accent/50">POST /api/v1/register</code>.
              The Console never generates keys. To revoke, use the Admin panel.
            </p>
          </div>
        </div>

        <div className="p-6 md:p-8 rounded-2xl bg-[#121214] border border-zinc-800 space-y-6 lg:col-span-2">
          <h3 className="text-lg font-bold text-white flex items-center gap-2 pb-4 border-b border-zinc-800/50">
            <Activity className="w-5 h-5 text-app-teal-accent" /> Server Status
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <StatusTile label="Capsules" value={status?.capsule_count?.toLocaleString() || '0'} />
            <StatusTile label="Storage" value={formatStorageMB(parseFloat(status?.total_storage_mb || '0'))} />
            <StatusTile label="Evidence Feed" value={`${status?.buffer_events?.toLocaleString() || '0'} events`} />
            <StatusTile label="Last Seal" value={status?.auto_seal?.last_seal ? new Date(status.auto_seal.last_seal).toLocaleTimeString([], { hour12: false }) : 'Never'} />
          </div>
          <div className="mt-4 p-4 rounded-xl bg-zinc-900 border border-zinc-800 space-y-3">
            <h4 className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest flex items-center gap-2">
              <ShieldCheck size={13} className="text-app-teal-accent" /> Auto-Seal Configuration
            </h4>
            <div className="flex flex-wrap gap-6">
              <div>
                <span className="text-[10px] text-zinc-600 uppercase">Enabled</span>
                <p className={cn("text-sm font-bold mt-0.5", status?.auto_seal?.enabled ? "text-app-teal-accent" : "text-zinc-600")}>{status?.auto_seal?.enabled ? 'Yes' : 'No'}</p>
              </div>
              <div>
                <span className="text-[10px] text-zinc-600 uppercase">Interval</span>
                <p className="text-sm font-bold text-white font-mono mt-0.5">{Math.floor((status?.auto_seal?.interval_seconds || 300) / 60)} minutes</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const SettingsRow: React.FC<{ label: string; value: string; mono?: boolean }> = ({ label, value, mono }) => (
  <div className="flex flex-col sm:flex-row sm:items-center justify-between py-3 border-b border-zinc-800/30 gap-2">
    <span className="text-sm text-zinc-500">{label}</span>
    <span className={cn("text-sm text-zinc-200", mono && "font-mono")}>{value}</span>
  </div>
);

const StatusTile: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="bg-app-bg border border-app-border rounded-xl p-4 space-y-2">
    <p className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">{label}</p>
    <p className="text-lg font-bold text-white font-mono">{value}</p>
  </div>
);

function formatStorageMB(mb: number): string {
  if (mb >= 1024 * 1024) return `${(mb / (1024 * 1024)).toFixed(1)} TB`;
  if (mb >= 1024) return `${(mb / 1024).toFixed(1)} GB`;
  return `${mb.toFixed(1)} MB`;
}
